import { useState } from "react";
import { ChevronRight, ChevronDown, LayoutGrid, List, EyeOff, Eye } from "lucide-react";
import { FileNode } from "../../lib/tauri";
import { FileIcon, ExtBadge, getExtColor } from "./FileIcon";
import { useT } from "../../i18n";

function formatSize(bytes: number | null): string {
  if (bytes == null) return "";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// ── Unity smart-filter ───────────────────────────────────────────────────────
// These are auto-generated by Unity and add noise${child.children.length - 50} without value when browsing.

const UNITY_SKIP_DIRS = new Set([
  "Library", "Temp", "Logs", "obj", ".vs", ".idea", ".git",
  "Builds", "Build", "UserSettings", "__pycache__",
]);

const UNITY_SKIP_EXTS = new Set([
  ".meta", ".csproj", ".sln", ".user", ".suo", ".tmp", ".pidb",
  ".userprefs", ".unityproj",
]);

const UNITY_SKIP_FILES = new Set([".DS_Store", "Thumbs.db", "desktop.ini"]);

function shouldHide(node: FileNode): boolean {
  if (node.is_dir) return UNITY_SKIP_DIRS.has(node.name);
  if (UNITY_SKIP_FILES.has(node.name)) return true;
  if (node.extension && UNITY_SKIP_EXTS.has("." + node.extension)) return true;
  return false;
}

function filterTree(node: FileNode, smart: boolean): FileNode {
  if (!smart || !node.children) return node;
  const filtered = node.children
    .filter((c) => !shouldHide(c))
    .map((c) => filterTree(c, smart));
  return { ...node, children: filtered };
}

// ── Node count guard — avoid rendering 10k+ nodes ───────────────────────────

const MAX_NODES = 2000;

function countNodes(node: FileNode): number {
  if (!node.children) return 1;
  return 1 + node.children.reduce((acc, c) => acc + countNodes(c), 0);
}

// ── Tree mode ────────────────────────────────────────────────────────────────

function TreeNode({ node, depth }: { node: FileNode; depth: number }) {
  const [open, setOpen] = useState(depth < 2);
  const color = getExtColor(node.extension ?? null);
  const t = useT();

  if (node.is_dir) {
    const childCount = node.children?.length ?? 0;
    return (
      <div>
        <button
          className="flex items-center gap-1.5 w-full text-left hover:bg-zinc-800/60 rounded px-1 py-0.5 group"
          style={{ paddingLeft: `${depth * 16 + 4}px` }}
          onClick={() => setOpen((v) => !v)}
        >
          <span className="text-zinc-600 shrink-0">
            {open ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
          </span>
          <FileIcon ext={null} isDir size={14} open={open} />
          <span className="text-xs text-zinc-200 truncate ml-0.5 font-medium">{node.name}</span>
          {childCount > 0 && (
            <span className="text-[10px] text-zinc-600 ml-auto shrink-0 pr-1 tabular-nums">
              {childCount}
            </span>
          )}
        </button>
        {open && node.children && (
          <div>
            {node.children.map((child, i) => (
              <TreeNode key={i} node={child} depth={depth + 1} />
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <div
      className="flex items-center gap-1.5 px-1 py-0.5 hover:bg-zinc-800/40 rounded group"
      style={{ paddingLeft: `${depth * 16 + 4}px` }}
    >
      <span className="w-3 shrink-0" />
      <FileIcon ext={node.extension ?? null} size={14} />
      <span className="text-xs truncate ml-0.5 flex-1" style={{ color }}>{node.name}</span>
      <div className="flex items-center gap-1.5 ml-auto shrink-0 pr-1 opacity-0 group-hover:opacity-100 transition-opacity">
        {node.extension && <ExtBadge ext={node.extension} />}
        {node.size != null && (
          <span className="text-[10px] text-zinc-500 tabular-nums">{formatSize(node.size)}</span>
        )}
      </div>
    </div>
  );
}

// ── Grid (folder browser) mode ───────────────────────────────────────────────

function FolderGrid({ root }: { root: FileNode }) {
  const [currentPath, setCurrentPath] = useState<FileNode[]>([root]);
  const current = currentPath[currentPath.length - 1];
  const sorted = [...(current.children ?? [])].sort((a, b) => {
    if (a.is_dir !== b.is_dir) return a.is_dir ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  const t = useT();

  return (
    <div className="flex flex-col gap-2">
      <div className="flex items-center gap-1 flex-wrap px-1 py-0.5 border-b border-zinc-800/60">
        {currentPath.map((crumb, i) => (
          <span key={i} className="flex items-center gap-1">
            {i > 0 && <ChevronRight className="h-3 w-3 text-zinc-700" />}
            <button
              className={`text-xs hover:text-zinc-100 transition-colors ${i === currentPath.length - 1 ? "text-zinc-200 font-medium" : "text-zinc-500"}`}
              onClick={() => setCurrentPath(currentPath.slice(0, i + 1))}
            >
              {crumb.name}
            </button>
          </span>
        ))}
      </div>
      {sorted.length === 0 ? (
        <p className="text-xs text-zinc-600 text-center py-6">{t("file_viewer_empty_folder")}</p>
      ) : (
        <div className="grid grid-cols-3 sm:grid-cols-4 gap-1">
          {sorted.map((child, i) => (
            <button
              key={i}
              className={`flex flex-col items-center gap-1.5 p-2.5 rounded-lg text-center transition-colors ${child.is_dir ? "hover:bg-zinc-800 cursor-pointer" : "cursor-default hover:bg-zinc-800/40"}`}
              onClick={() => { if (child.is_dir) setCurrentPath((prev) => [...prev, child]); }}
            >
              <FileIcon ext={child.is_dir ? null : (child.extension ?? null)} isDir={child.is_dir} open={false} size={28} />
              <span className="text-[10px] text-zinc-300 leading-tight line-clamp-2 break-all w-full">{child.name}</span>
              {child.size != null && !child.is_dir && (
                <span className="text-[9px] text-zinc-600 tabular-nums">{formatSize(child.size)}</span>
              )}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Main export ──────────────────────────────────────────────────────────────

interface FileTreeViewerProps {
  root: FileNode;
  label?: string;
  maxH?: string;
  /** When true, shows the smart-filter toggle button. Default: false */
  showFilterToggle?: boolean;
  /** Initial smart-filter state. Default: false */
  defaultFiltered?: boolean;
}

export function FileTreeViewer({
  root,
  label,
  maxH = "max-h-72",
  showFilterToggle = false,
  defaultFiltered = false,
}: FileTreeViewerProps) {
  const [mode, setMode] = useState<"tree" | "grid">("tree");
  const [smartFilter, setSmartFilter] = useState(defaultFiltered);
  const t = useT();

  const displayRoot = filterTree(root, smartFilter);
  const nodeCount = countNodes(displayRoot);
  const tooLarge = nodeCount > MAX_NODES;

  // If the tree is still too large even after filtering, truncate children of
  // top-level directories so we don't lock the browser.
  const safeRoot: FileNode = tooLarge
    ? {
        ...displayRoot,
        children: displayRoot.children?.map((child) => ({
          ...child,
          children: child.children && child.children.length > 50
            ? [...child.children.slice(0, 50), {
                name: t("file_viewer_truncated", { count: child.children.length - 50 }),
                path: child.path + "/__truncated__",
                is_dir: false, extension: null, size: null, children: null,
              }]
            : child.children,
        })) ?? null,
      }
    : displayRoot;

  return (
    <div className="flex flex-col gap-2">
      <div className="flex items-center justify-between">
        {label && <p className="text-[11px] font-semibold text-zinc-500 uppercase tracking-wider">{label}</p>}
        <div className="flex items-center gap-1 ml-auto">
          {/* Smart filter toggle */}
          {showFilterToggle && (
            <button
              onClick={() => setSmartFilter((v) => !v)}
              title={smartFilter ? "Show all files" : "Hide Unity-generated files (.meta, Library/, Temp/, …)"}
              className={`flex items-center gap-1.5 h-6 px-2 rounded text-[10px] font-medium transition-colors ${
                smartFilter
                  ? "bg-zinc-700 text-zinc-200"
                  : "text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800"
              }`}
            >
              {smartFilter ? <Eye className="h-3 w-3" /> : <EyeOff className="h-3 w-3" />}
              {smartFilter ? t("file_viewer_all_files") : t("file_viewer_smart_filter")}
            </button>
          )}
          {/* View mode */}
          <button
            className={`h-6 w-6 flex items-center justify-center rounded transition-colors ${mode === "tree" ? "bg-zinc-700 text-zinc-200" : "text-zinc-500 hover:bg-zinc-800"}`}
            onClick={() => setMode("tree")}
            title={t("file_viewer_tree")}
          >
            <List className="h-3.5 w-3.5" />
          </button>
          <button
            className={`h-6 w-6 flex items-center justify-center rounded transition-colors ${mode === "grid" ? "bg-zinc-700 text-zinc-200" : "text-zinc-500 hover:bg-zinc-800"}`}
            onClick={() => setMode("grid")}
            title={t("file_viewer_flat")}
          >
            <LayoutGrid className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {/* Node count info */}
      {tooLarge && !smartFilter && (
        <div className="flex items-center gap-2 rounded-md border border-amber-900/40 bg-amber-950/20 px-3 py-2">
          <EyeOff className="h-3.5 w-3.5 text-amber-500 shrink-0" />
          <p className="text-[11px] text-amber-400">
            Large tree ({nodeCount.toLocaleString()} nodes). Enable <strong>Smart filter</strong> to hide generated files and speed up rendering.
          </p>
        </div>
      )}

      <div className={`bg-zinc-900/60 rounded-lg border border-zinc-800 overflow-auto ${maxH} p-1`}>
        {mode === "tree" ? <TreeNode node={safeRoot} depth={0} /> : <FolderGrid root={safeRoot} />}
      </div>

      {nodeCount > 100 && (
        <p className="text-[10px] text-zinc-700 text-right tabular-nums">{nodeCount.toLocaleString()} items</p>
      )}
    </div>
  );
}